# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ed3d6662b861554c951a502f355475b4518409a576e53c3c07760d838e3021ac81b0f13dc938d36ffe50c241bd448b8c6a3e334a4cfcdb13f69ababcd306629

test:
  secret_key_base: 4424f02ac86b6d15b2ab9e5742e264650212d7ae30215cebd2e56f7696d0af18cb741ca4f4a11088b77d9974a5b10ada5cc8ee4931d4e373d969a8269323663f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
